language: node_js
node_js:
- 4.2.2
deploy:
  provider: heroku
  api_key:
    secure: PV8QVdjZS2UVEqk+nhYJdce4T7cnahTOMAAhGiuC/X1/0f9IuyvAI3cycbzrhd7ClJ/aZJh59IagaBKYMNefooOhhObBAemcEihI2A3lJ0tyeY5Mlf/flMWVvLovsJMYFVn0PJ80FI85HcP0MmcxrvYMzh9K/VDJ40eoL6K62l9rv9srqjbYjZXOhP6E2M5wnirwfHTWmA7sAiccdPDWcFmRjv8k9d6cPd1giF7rr0kvrbq9f1N2dGSXsVV15ey8zikid+nV0LBA/iaj6B2C9h/2RWtmV7d9t1vL573IfGhSKk9fzFOQRUbeJ59DuWgIxaiIZrES5ujefB5+DGY5zm5T3RTv/lAbOhgGHbtzwp+XhvlZt7eenrD2dNZSGZ0cx1xEJsDni1ApjlnGBIryzcXVrZJG5VxzK2/diIo5Czp0fs1keERNfXb3uhAISXL7q4IQc9cHC3AsOd4V8Mak6ERaSEA0G+blHPSd/M8DjPS2j8XYdy1IAELVSOnhr5DIaKdr4/0BWj2zpsNCgB28TcgYdN44Axm8bIJllvySig2pS/OIaswpyQ4y4GNnins5Rg0bGXiKRa6RkuY2qcMdntmjj6bj7gmOgpzG8IYWovn6+CqVSr+GvhI/qTG2EPV1vCH24hj25HdmLziF1V+AFtREuA2tWJE3tedoIUVZVOE=
  app: mp-automation
  on:
    repo: mazzur/automation
