language: node_js
node_js:
- 4.2.2
deploy:
  provider: heroku
  api_key:
    secure: EZRzMju58XzH0+Y0z/b1mDN7CrtnrmHuDC2ahL2mi2JnTbSvAr56riMGdDxHBPwuelTcxDBNCSCoelOG+3Vf837vVihn4pnWSc0R/YvwO7tFCnsUHdBfBh+oQT4Hw9R0qxDaBA4HYWYgHoRSsawAJ8SrOQa+RvVqNYvLFOAJkmC6s7vc9TTUjQbGfSel6t2budhkc7bH8++mj6SQkEDM61vnnOj9abIHRB1Z9GsCwx68fS9vGe7ZlR2dxQ31vbWfLYKykHXo/mKIMUFbCuxQ0PG8SCfzVzsFCleHwtRrHkt7aOneRZ4mMBDBm03DsPGrx3ml12UpqW9Qpzk4lsB3K5M1vBK05XP9tkN9QSHo0RRLBYu0mwE5pauxYl3mzzAtsR+/53tccjK7Jt6Qh48vDLjumougzTbQRp3wgo41Xnmd9XvV2sasn2QcYwExywp/SvwDabW1cJCj9AOuG+YtgApLftLfAeqjvodF3OnyO2Xw+kmQiEXwuMVg55YWX7tD/ellZqeobct38UwPqzCiYehSJ2mi3Ax8ZpfzL1+Sa99+4CCmhKNX7msPnFJI+8bGTGcH7nPvvNRAPp/EdmUQ++tZBmNHTUbB6vET7u1Ox8YsAL4dmyQCVnVrPG2Kbm95R3gFX3AqsRDdMVkAdqlstsxcapOw+3KvfwdWcNPjbe8=
  app: mp-automation
  on:
    repo: mazzur/automation
