language: node_js
node_js:
- 4.2.2
before_script:
- npm i -g gulp
script: gulp && karma start karma.conf.js
after_script: gem install heroku
deploy:
  provider: heroku
  app: mp-automation
  on:
    repo: mazzur/automation
  api_key:
    secure: QTE+K2uZ+WC3OBasOyK3c+BDIxvK+J1LAflXKufoOBqcm/2XDgFN7rM8NLA+C5bAoH+tHP5sRwEbCc9NAGddgFJDiqljF2UvikhzkPDB84CJTXI3YBkBLD911EJbAJKB0vMbSPrc+6t7eYh/3VCoFs5Q98OCPsFM6ttVBfnnWhTpB74YT5kU9VnMZYLQOVywqTTzjKWFs9werJmmthFB2MzrffK9pYPF4sQQpgP7gu4W55GPNOjWL+KaqwOC3jPNV8F1HCu2RtHHss+E4rzLBXIxVtxpbgBH2gM0weX+k/iGmqmPVyDAWl4R3vhiWIesR1+K1J14iZjqyU3sINPprbjxyf9SdIwWds4N9rbESpcbyIUOlqObzF6G5vq7j48hCQMnDNQ5qTiHs5vpD081r245V/pwTmNxlVkOiHLWpoCkCiA2Vxm4eB/4a3fQLDtLj+jCTxHa0oFumaV046vggoIDJePahBcym4vq4vI+bR+SQKgbOt9mEy98JKmSRoRbC1oSTiF0drz/g+1elqNtWlmExVMT/thPI7IBHhbK50Km7Aj7PD6zFeAjDS+xmfBUGtT+Xc8mGV7sHxUb1pkFFPtHfTwrQZTLEytkIdpAIFDTu3jxeYeV5TJNkXWMr/uuSEB0etqAb1FvBY6OZSjTFA2tB7azKpiaxDSH5eAYmpM=
