language: node_js
node_js:
- 4.2.2
deploy:
  provider: heroku
  app: mp-travis-heroku
  api_key:
    secure: CG+rvPvL2r4CtwOeGS/aV1iDTFQknxyqW9d6BUGHY2dxEWqkM5tG73BA8ZMoetHamuto+jFO0msxKfYEFD7JumJW85q1A1ZYMfrLlOwnD8PP4cZCZRJtkTsfSrFEuJaTcns7GyTfIGVI8F178M2akK/SCnarkXBUAYF5lVdwHXOMUbTFnzzY3hNDBh/WD7hx47iEUn3vsZDVGLDVfB822rfFpwKMU8yuXAKkf6WsDHtspM3CiKTmE+5kfpiQOp5EVThYx1S1cs4nZwb2ZAL1hlyU7bHyNZRtYD5ZHJrrVwlBOayi3zv0CjcNHKZC9cU22IfimdjfyWfM2OJnISaaz710XoONCK3DBbenSJwxncmkA4cF36Md+U0IHkK5u984hPYgg/cXlzmiJ7d7r7QHsL0oXys2LKZrI51Lj8KsNU8zmetHldg8z+RLlqS7ledy/Bcvd2SOydkHY9g2a2/7fxIr0nrULs6hevRUiCG4hOKRVZZ9BOPHA00JFTggAI/Ukqa8gtDhRqgd2tEisHV/w5r6bGXHyPEQ5XVcT4CgepFeiN357zsgkS53q+swsQnC0WW4/+zt+tXNEjEM6yTFyWyIrN2CLvPRJPC+3grJ5hbLbfVNBELTEQCSPYIDlyZVt0M5YBSuR/iPLM3IT+a+uzz3d39chSd9wDZ2AdY/KJs=
